clustering_params:
  # Supported values for distance_metric include: "Euclidean", "Manhattan", "Chebyshev" (though Chebyshev is included in the code, the validation currently only allows "Euclidean" or "Manhattan").
  distance_metric: "Euclidean"
  initialization_method: "KMeansPlusPlus"
  initial_k: 4

logging:
  level: "info"

output_path: "data"
