clustering_params:
  # Supported values for distance_metric include: "Euclidean", "Manhattan", "Chebyshev"
  distance_metric: "Euclidean"
  initialization_method: "Random"
  initial_k: 4

output_path: "data"
